##Para recuperar todos los productos
GET http://localhost:5000/products
###Para recuperar un producto por el id

GET http://localhost:5000/products/2

###Para recuperar por tipo
GET http://localhost:5000/products?type=camiseta

###Para crear un producto
POST http://localhost:5000/products
Content-Type: application/json

{
        
        "name": "Producto 3333",
        "description": "Descripción del Producto 3",
        "price": 1,
        "imageUrl": "https://via.placeholder.com/200x200?text=Product3",
        "type": [
          "camiseta"
        ]
      }

###Actualizar una pelicula
PATCH http://localhost:5000/products/2
Content-Type: application/json

{
  "name": "Producto4455933",
        "description": "Descripción del Producto 3",
        "price": 134,
        "imageUrl": "https://via.placeholder.com/200x200?text=Product3",
        "type": [
          "camiseta"
        ]
       
}
