##Para recuperar todos los productos
GET http://localhost:5000/products
###Para recuperar un producto por el id

GET http://localhost:5000/products/e5e43138-a1d6-11ee-ad00-489ebd108d78

###Para recuperar por tipo
GET http://localhost:5000/products?type=pantalon

###Para crear un producto
POST http://localhost:5000/products
Content-Type: application/json

{
        
        "name": "Producto pant",
        "description": "Descripción del Producto 40",
        "price": 2,
        "imageUrl": "https://via.placeholder.com/200x200?text=Product3",
        "type": [
          "pantalon"
        ]
      }


###Borrar un producto
DELETE http://localhost:5000/products/b368ab36-9fac-11ee-b927-489ebd108d78

###Actualizar una pelicula
PATCH http://localhost:5000/products/e5e43138-a1d6-11ee-ad00-489ebd108d78
Content-Type: application/json

{
  "name": "Product final",
        "description": "Descripción del Producto 43",
        "price": 300,
        "imageUrl": "https://via.placeholder.com/200x200text=Product4",
        "type": [
          "camiseta"
        ]
       
}
